---
dist: trusty
sudo: false

language: python
python: '2.7'
cache: pip

matrix:
  fast-finish: true

env:
  - TEST_RUN='./tests/travis_python_tests'
  - TEST_RUN='./tests/travis_shell_tests'

install:
  - pip install -U .

script: "$TEST_RUN"
