---
- name: create .ssh directory on source host
  sudo: yes
  sudo_user: "{{ from_user }}"
  delegate_to: "{{ from_host }}"
  file: >
    state=directory
    path=~/.ssh
    mode=0750

- name: generate credentials on source host
  sudo: yes
  sudo_user: "{{ from_user }}"
  delegate_to: "{{ from_host }}"
  command: >
    ssh-keygen -t dsa -N ""
    -f ~/.ssh/temporary_id
    creates=~/.ssh/temporary_id

- name: gather public key from source host
  sudo: yes
  sudo_user: "{{ from_user }}"
  delegate_to: "{{ from_host }}"
  command: >
    cat ~/.ssh/temporary_id.pub
  register: temporary_pubkey

- name: place public key on destination host
  sudo: yes
  sudo_user: "{{ to_user }}"
  delegate_to: "{{ to_host }}"
  authorized_key: >
    user={{ to_user }}
    key="{{ temporary_pubkey.stdout }}"
