---
- name: remove temporary credentials from source host
  sudo: yes
  sudo_user: "{{ from_user }}"
  delegate_to: "{{ from_host }}"
  file: >
    state=absent
    path=~/.ssh/{{ item }}
  with_items:
    - temporary_id
    - temporary_id.pub

- name: remove public key from destination host
  sudo: yes
  sudo_user: "{{ to_user }}"
  delegate_to: "{{ to_host }}"
  authorized_key: >
    state=absent
    user={{ to_user }}
    key="{{ temporary_pubkey.stdout }}"
