---
  # Repo and tor are installed in common role
- include: create_app_dirs.yml

- include: app_install_fpf_deb_pkgs.yml
  when: securedrop_app_install_from_repo

- include: initialize_securedrop_app.yml

- include: install_and_harden_apache.yml
  when: securedrop_app_configure_apache

- include: configure_securedrop_worker.yml

- include: setup_cron.yml

- include: configure_haveged.yml
