---

- include: common.yml tags=role_postgresql
- include: client.yml tags=role_postgresql
- include: server.yml tags=role_postgresql
  when: >
    inventory_hostname in groups.database
- include: master.yml tags=role_postgresql
  when: >
    inventory_hostname in groups.database_master
- include: slave.yml tags=role_postgresql
  when: >
    inventory_hostname in groups.database_slaves
